<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIqC69jD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIqC69jD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIqC69jD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIqC69jD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIqC69jD\App_KernelDevDebugContainer([
    'container.build_hash' => 'IqC69jD',
    'container.build_id' => '86e72111',
    'container.build_time' => 1630438863,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIqC69jD');
