<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN1Co5wL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN1Co5wL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN1Co5wL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN1Co5wL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN1Co5wL\App_KernelDevDebugContainer([
    'container.build_hash' => 'N1Co5wL',
    'container.build_id' => 'ccdf487c',
    'container.build_time' => 1631266527,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN1Co5wL');
