<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBvxjvmF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBvxjvmF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBvxjvmF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBvxjvmF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBvxjvmF\App_KernelDevDebugContainer([
    'container.build_hash' => 'BvxjvmF',
    'container.build_id' => 'caf266e4',
    'container.build_time' => 1628839220,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBvxjvmF');
